# Generated by Django 2.2.4 on 2019-09-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_api', '0003_auto_20190921_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
