# Generated by Django 2.2.4 on 2019-09-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_api', '0004_auto_20190921_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
