# Generated by Django 2.2.4 on 2019-10-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_api', '0009_auto_20191012_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
