# Generated by Django 2.2.4 on 2019-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_api', '0010_community_community_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_image',
            field=models.FileField(default='', upload_to='api/'),
        ),
    ]
